Add dummy of gralloc_handle_*
error: hardware/qcom-caf/sm8250/display/gralloc/Android.bp:*:1:
"libgralloccore" depends on undefined module
"gralloc_handle_has_reserved_size_defaults".
"gralloc_handle_has_custom_content_md_reserved_size_defaults"
"gralloc_handle_ubwcp_format_defaults"

Signed-off-by: BrightTwikling <DFSJbbba5@gmail.com>